config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"   


  
  get "login" , to: "sessions#new"
  post "login" , to: "sessions#create"
  delete "logout" , to: "sessions#destroy"
    
  get "signup" , to: "users#new"
    
  resources :tasks
  resources :users,only: [:create]
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  
  

  
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    validates :content,presence: true, length: { maximum: 255 }

    validates :status,presence: true, length: { maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }

  
  validates :name, presence: true, length: {maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
                    
  has_secure_password
  
  #関係追加
  has_many :tasks
  #dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

    
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_path
    end
  end
  
  def counts(user)
    @count_tasks = user.tasks.count
  end
  
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_path
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
    
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_path  
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  before_action :set_task, only: [:show, :edit, :update, :destroy]

      
  def index

      @tasks = current_user.tasks.order(id: :desc)
  end
    
  

  def show
      set_task
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    
    if @task.save
      flash[:success] = "正常に作成されました"
      redirect_to tasks_path
    
    else
      flash.now[:danger] = "作成に失敗しました"
      render :new
    end
  end

  def edit
    set_task
  end

  def update
    set_task
    
    if @task.update(task_params)
      flash[:success] = "正常に更新されました"
      redirect_to tasks_path
    
    else
      flash.now[:danger] = "更新されませんでした"
      render :edit
    end
  end

  def destroy
    set_task
    @task.destroy
    
    flash[:success] = "正常に削除されました"
    redirect_to tasks_path
  end
  
  private
  def set_task
    @task = Task.find(params[:id])
  end
  
  def task_params
    params.require(:task).permit(:content, :status)
  end

  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_path
    end
  end

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_user_logged_in, only: [:index, :show]
    
 # def index
  #end

  #def show
   # @user = User.find(params[:id])
    #@tasks = @user.tasks.order(id: :desc).page(params[:page])
  #end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "ユーザーを登録しました"
      redirect_to tasks_path
    
    else
      flash.now[:danger] = "ユーザー登録に失敗しました"
      render :new
    end
  end
end


private

def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end 
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type,message| %>
    <div><%= message %></div>
<% end%>

app/views/layouts/_flash_tasks.html.erb
<% flash.each do |task_type,task| %>
    <div><%= task %></div>
<% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang ="ja">
  <head>
    <title>KadaiTasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class= "container">
      <%= render "layouts/flash_messages" %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |f| %>

  <% if task.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  
    <%= f.label :content, "タスク内容：" %>
    <%= f.text_field :content %>
    


    <%= f.label :status, "状況：" %>
    <%= f.text_field :status %>
    
    <%= f.submit "作成" %>
<% end %>

app/views/tasks/edit.html.erb
<h1>id: <%= @task.id %> の編集ページ</h1>

<%= render "form", task:@task %>

<%= link_to "一覧に戻る",tasks_path %> 

app/views/tasks/index.html.erb
<% if logged_in? %>
<h1>タスク一覧</h1>
<ul>
  <% @tasks.each do |task| %>
    <li><%=link_to task.id, task %> : <%= task.content %> : <%= task.status %></li>
  <% end %>
</ul>

<%= link_to "新しいタスクの作成",new_task_path %>


<%= link_to "ログアウト", logout_path, method: :delete %>



<% else %>

<%= require_user_logged_in %>

<% end %>

app/views/tasks/new.html.erb
<h1>タスク作成ページ</h1>

<%= render "form", task:@task %>

<%= link_to "一覧に戻る",tasks_path %> 

app/views/tasks/show.html.erb
<h1>id: <%= @task.id %> <%= @task.content %> の詳細</h1>
<p>状況：<%= @task.status %></p>


<%= link_to "一覧に戻る", tasks_path %>
<%= link_to "このタスクを編集する", edit_task_path(@task) %>
<%= link_to "このタスクを削除する", @task, method: :delete, data: {confirm: "本当に削除していいですか？" } %>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>


<%= form_with(model: @user, local: true) do |f| %>
  <%= render "layouts/error_messages", model: f.object %>

  
  <%= f.label :name, "ユーザー名：" %>
  <%= f.text_field :name %>
    
    
  <%= f.label :email, "Emailアドレス：" %>
  <%= f.email_field :email %>
    
  <%= f.label :password, "パスワード：" %>
  <%= f.password_field :password %>
    
    
  <%= f.label :password_confirmation, "パスワード確認" %>
  <%= f.password_field :password_confirmation %>
  
  <%= f.submit "登録" %>
  
<% end %>


<%= link_to "戻る" , login_path %>
    
    